export default {
  MOVETO_SECTION: "MOVETO_SECTION",
  COPY_RECEIVED: "COPY_RECEIVED",
  IMG_LOADED: "IMG_LOADED",
  CHANGE_SCREEN_WIDTH: "CHANGE_SCREEN_WIDTH",
  TOGGLE_MENU: "TOGGLE_MENU",
  CHANGE_SCROLL_INDICATOR: "CHANGE_SCROLL_INDICATOR",
  SELECT_WORK: "SELECT_WORK",
  TOGGLE_WORK_MODAL: "OPEN_WORK_MODAL"
};
